GPUS: (0,1,2,3)
WORKERS: 4
PRINT_FREQ: 1

DATASET:
  DATASET: ped2
  ROOT: 'C:\College work\astnet-main\ASTNet\datasets'
  NUM_FRAMES: 5
  FRAME_STEPS: 2
  LOWER_BOUND: 100

TRAIN:
  BATCH_SIZE_PER_GPU: 2
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 10
  RESUME: true
  OPTIMIZER: 'adam'
  LR_TYPE: 'multistep'
  LR: 0.0002
  LR_STEP: [80,100]
  IS_TRAIN: true

TEST:
  BATCH_SIZE_PER_GPU: 1
  IS_TRAIN: false

MODEL:
  NAME: 'wrn38'
  INIT_WEIGHTS: true
  PRETRAINED: 'C:\College work\astnet-main\ASTNet\datasets\seg_weights\wider_resnet38.pth'
  IMAGE_SIZE:
    - 256
    - 256
  MEMORY_SIZE: 5
  ENCODED_FRAMES: 4
  DECODED_FRAMES: 0
  EXTRA:
    FINAL_CONV_KERNEL: 3
